### ISSUE TITLE
dynamic calc miscalculation

### ISSUE THREAD

**Issue by Chasen-Zhang** [aeagle/react-spaces#110]
**Describe the bug**

This happens when you drag up and down
![image](https://user-images.githubusercontent.com/15354455/155663388-9a4872d5-7793-4951-b894-1605a1009e8c.png)

BottomResizable it is hidden !

Out of visual range

![image](https://user-images.githubusercontent.com/15354455/155664138-7f2ccdeb-297a-4757-b22e-6fd8e9669407.png)
It turned out to be a negative number

**Comment by aeagle** [comment]
Hi @Chasen-Zhang 

Could you provide a Code Sandbox reproducing the issue? I've tried reproducing in the same issue in the latest version Chrome but don't see the same behaviour.

It would also be helpful to know:

- The version of react spaces you are using
- The browser that exhibits this behaviour

**Comment by hkl921010** [comment]
me too

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/173313331-be2a12a4-278f-45b5-aea0-
LeftResizable components also have problems


> Reference

 "react-spaces": "^0.3.4",

**Comment by Chasen-Zhang** [comment]
It's not going to happen. I can't give it to demo

**Comment by Chasen-Zhang** [comment]
This can happen if you drag fastly

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/173358252-0097f456-dfe6-40f0-b2e5-0d1b276047ef.png)

**Comment by Chasen-Zhang** [comment]
You might not know the boundary conditions

**Comment by Chasen-Zhang** [comment]
![image](https://user-images.githubusercontent.com/15354455/173359215-76c3f9ee-4ef9-44e7-a25a-e910140fe90c.png)
I guess this code have bugs

**Comment by Chasen-Zhang** [comment]
> Hi @Chasen-Zhang
> 
> Could you provide a Code Sandbox reproducing the issue? I've tried reproducing in the same issue in the latest version Chrome but don't see the same behaviour.
> 
> It would also be helpful to know:
> 
> * The version of react spaces you are using
> * The browser that exhibits this behaviour

mac chrome latest

**Comment by aeagle** [comment]
@Chasen-Zhang I identified a race condition in the resize operation of spaces in relation to issue #107. There is a possibility that this is the same issue you are experiencing. I've released a hotfix in `v0.4.1`.

**Comment by aeagle** [comment]
@Chasen-Zhang Hi. Did you manage to test this fix?

**Comment by aeagle** [comment]
Going to close this as resolved. Feel free to reopen if you are still having issues.
