### ISSUE TITLE
add sourcecode to lorem-ipsum demo

### ISSUE THREAD

**Issue by awb99** [aeagle/react-spaces#111]
On the homepage https://www.allaneagle.com/projects/react-spaces you show a complex example 
(a table with lorem-ipsum. Could you add the sourcecode to this demo somewhere? Thanks!!

**Comment by aeagle** [comment]
@awb99 Here's a sandbox with the code - https://codesandbox.io/s/fancy-mountain-rpgkwu?file=/src/App.tsx. I am going to add a link to this by the demo on the site too.
