### ISSUE TITLE
bug: resizeType  always  is "resize-right"

### ISSUE THREAD

**Issue by Chasen-Zhang** [aeagle/react-spaces#122]
**Describe the bug**

resize to the left is "resize-right"

resize to the right still  is "resize-right"
![image](https://user-images.githubusercontent.com/15354455/173304465-6297b724-da0b-417a-a768-5c3edef8d2f1.png)

**Comment by aeagle** [comment]
@Chasen-Zhang This is by design. The `resizeType` refers to the resizable edge of the space and not the direction of resize being changed by mouse/touch. You could calculate this in your code by keeping track of the initial size and comparing it with the final size.
