### ISSUE TITLE
Dynamic size not working correctly

### ISSUE THREAD

**Issue by strass** [aeagle/react-spaces#21]
I wanted to set up something like this, where the left bar can be toggled between 50px and 100px, but this is not working – the other elements don't react:

```jsx
const AppLayout: FunctionComponent = () => {
  const [expanded, setExpanded] = useState(false);
  return (
    <ViewPort>
      <Left
        size={!expanded ? 50 : 100}
      >
        ...
      </Left>
      <Fill>...</Fill>
    </ViewPort>
```

is there a "right" way to do this?

https://codesandbox.io/s/react-shapes-0v1g3?fontsize=14

**Comment by aeagle** [comment]
@strass Hiya. I've just released a version (0.1.11) which should fix this. I wasn't taking into account changes to the size property on the components. Let me know if it works as expected now.

**Comment by strass** [comment]
It does indeed! Thanks for the speedy response - I figured I was doing something wrong :-P

**Comment by aeagle** [comment]
Glad that sorts things out for you. I'll close the issue.
