### ISSUE TITLE
Hooking into start/finish resize events

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#32]
**Is your feature request related to a problem? Please describe.**
I know `<Info />` lets you tap into `height`/`width`, but not necessarily event start/finish.

We're moving from [react-split-pane](https://www.npmjs.com/package/react-split-pane) which allowed us to listen for a start/finish of resize. Specifically, if a user resizes past a certain point we want to handle it ourselves, but we want to allow users to trigger the action via ending their drag event, rather than trying to guess at when we should respond. Perhaps this is already possible in a way I'm overlooking.

**Describe the solution you'd like**
Ability to add props such as `onDragStarted` and `onDragFinished` to a space. (Those are the names used by `react-split-pane`.

**Describe alternatives you've considered**
A timer based solution to listen for no changes to size for X seconds, but definitely not ideal.

**Comment by aeagle** [comment]
@Slapbox The drag start and drag end events would definitely be the way to go and should not be hard to implement. I will see if I can get these into an upcoming release.

**Comment by Slapbox** [comment]
Thanks @aeagle! I'm looking forward to it!

**Comment by aeagle** [comment]
@Slapbox I've added resize event callback properties to resizable spaces in version 0.1.18:

onResizeStart: () => {}
onResizeEnd: (newSize) => {}

Hopefully this should also allow you to attempt the solution at https://github.com/aeagle/react-spaces/issues/36#issuecomment-543392599 on issue #36.

**Comment by Slapbox** [comment]
That's awesome! Thank you! I'll give it a shot soon.
