### ISSUE TITLE
Document minimumSize property

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#35]
I know it's in the examples, but I think you'd agree that it probably deserves to be under "Useful Properties" on the About page.

I don't think there's a `maximumSize` property, but that would be really useful too!

Again, very cool project! Thanks for sharing!

**Comment by aeagle** [comment]
@Slapbox - the maximumSize property does exist on resizable spaces. I've added both of them to the documentation - https://www.allaneagle.com/projects/react-spaces
