### ISSUE TITLE
Changing zIndex dynamically has no effect

### ISSUE THREAD

**Issue by thekapadia** [aeagle/react-spaces#42]
@aeagle When I **change the `zIndex` dynamically, it has no effect** while trying to achieve layering without wrapping into the `Layer` component.

Demo
- https://codesandbox.io/s/competent-tesla-myp6e
- https://codesandbox.io/s/elegant-currying-g0ijr

**Comment by aeagle** [comment]
@thekapadia Thanks for the examples. I'll look into this shortly. I can see the space has registered a move into a different layer, however, the spaces already in the target area have not been updated to take into account the new space.

**Comment by thekapadia** [comment]
@aeagle And somewhere even the `calc()` is going wrong. Spaces are being misplaced. 

Here's what I'm trying to achieve in my project using React Spaces.
https://codesandbox.io/s/icy-dust-ouf6l

I'm trying to get **_pinnable_** panels, which I can _Open_ or _Close_ (no change in `zIndex`, only `size` changes), and _Pin_ or _Unpin_ (change in `zIndex` and `size`, both).

**Comment by aeagle** [comment]
@thekapadia Thanks for the sandbox. I'll have a play later to try to resolve.

**Comment by aeagle** [comment]
@thekapadia I've released version `0.1.19` which should resolve this.

Here is an example based on your original sandbox - https://codesandbox.io/s/patient-water-fpe2c?fontsize=14

**Comment by thekapadia** [comment]
Thanks @aeagle for the fix and quick turnaround. Really appreciate.

One more thing, I just noticed another issue.

Check https://codesandbox.io/s/elated-bose-obcq3 (forked from your example above).

I added `resizable={true}` to the first **Left** space.

Now do the following.
1. Click _Open_ in the left space.
3. Stretch/expand the left space by drag-and-resize.
2. Click _Pin_ in the left space.

Observe the blank white space being generated.

**Comment by thekapadia** [comment]
Hi @aeagle - just passing by to see if there's any update on this `resizable` issue. Thanks!

**Comment by aeagle** [comment]
Hi @thekapadia. I'm in the middle of working on a new release so I'm hoping to get this fixed and a few other issues in that. Hopefully not too long now.

**Comment by thekapadia** [comment]
> Hi @thekapadia. I'm in the middle of working on a new release so I'm hoping to get this fixed and a few other issues in that. Hopefully not too long now.

Hi @aeagle - just curious to know a tentative release date.

**Comment by aeagle** [comment]
Hi @thekapadia. I'm struggling with some state issues at the moment. Rest assured once I sort I'll release. I'm planning to look at this and the other issues this weekend so hopefully then. Thanks for the patience.

**Comment by aeagle** [comment]
Hi @thekapadia. I've produced an alpha package which has a major rework of the state kept within the components which should resolve a lot of the out-of-sync problems experienced. Check this sandbox out in regards to this issue - https://codesandbox.io/s/agitated-framework-n91kl. The package alpha version is `v0.1.20-alpha.3`.

Once I get feedback on this and some of the other issues I will release a non-alpha version.

**Comment by thekapadia** [comment]
@aeagle I'm getting these errors when I set `resizable={true}`. I'm using `0.1.20-alpha.3`.

```
React has detected a change in the order of Hooks called by null. This will lead to bugs and errors if not fixed. For more information, read the Rules of Hooks: https://fb.me/rules-of-hooks

   Previous render            Next render
   ------------------------------------------------------
1. useRef                     useRef
2. useContext                 useContext
3. useState                   useState
4. useState                   useState
5. useRef                     useRef
6. useRef                     useRef
7. useContext                 useContext
8. useCallback                useCallback
9. useEffect                  useEffect
10. useEffect                 useEffect
11. useEffect                 useEffect
12. useEffect                 useEffect
13. useEffect                 useEffect
14. useEffect                 useEffect
15. useCallback               useCallback
16. undefined                 useCallback
```

and 

`react-dom.development.js:15409 Uncaught Invariant Violation: Rendered more hooks than during the previous render.`

**Comment by aeagle** [comment]
@thekapadia `0.1.20-alpha.4` should fix this.

**Comment by thekapadia** [comment]
Hi @aeagle - I tested with `0.1.20-alpha.4`, the above issues got resolved. 

But I noticed one small but important anomaly.

In the example, https://codesandbox.io/s/frosty-sky-5b5bm - when I open/close the **Left Pinnable** pane - the `constructor()` of `<Sample label="Left Pinnable" />` is called everytime (component is recreated) when `resizable={true}`. This is causing my component `Sample` to lose its state.

When you set `resizable={false}`, `constructor()` of `<Sample label="Left Pinnable" />` is not called.

**Comment by aeagle** [comment]
Hey @thekapadia. Glad the version fixed this issue. I think it's worth now creating a separate issue for your re-render problem.
