### ISSUE TITLE
Support passing mouse events from Space to its internal component (spaces-space-inner)

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#43]
**Is your feature request related to a problem? Please describe.**
I'd like to track the X position of a user's mouse relative to `<ViewPort />, but that requires wrapping it like:

```js

<div
  onMouseMove = {this.onMouseMove}>
  <ViewPort />
</div>
```

**Describe the solution you'd like**
Pass React event handlers to the internal component, the one with the className `spaces-space-inner`

**Describe alternatives you've considered**
Wrapping `<ViewPort />` with a `div` to handle events, or the reverse using `<ViewPort />` to wrap a `div` that handles events. I'm not sure what side effects throwing extra wrappers inside of `ViewPort,` but above the spaces it contains can cause, if any.

**Additional context**
This might be more of an issue with `<Fixed />`. Not really sure.

Even if there are no side effects, avoiding the need to add more nested `div`s would be great. React-Spaces provides amazing functionality, but it can make inspecting the DOM a bit more confusing since even the simplest implementation involves adding 5 layers of `div`s, plus the sibling-level resize handles.

Also produces nicer code overall:

```js
// Currently to handle events
<Spaces.ViewPort>
    <div onMouseMove={this.onMouseMove}>
        <Spaces.LeftResizable {...{ size, minimumSize, }}>
            <div onClick={this.onClick}>
                {this.props.children[0]}
            </div>
        </Spaces.LeftResizable>
        <Spaces.Fill>
            {this.props.children[1]}
        </Spaces.Fill>
    </div>
</Spaces.ViewPort>
```
**Versus**
```js
// Spaces that can pass event handlers would be nifty
<Spaces.ViewPort onMouseMove={this.onMouseMove}>
    <Spaces.LeftResizable {...{ size, minimumSize, }} onClick={this.onClick}>
        {this.props.children[0]}
    </Spaces.LeftResizable>
    <Spaces.Fill>
        {this.props.children[1]}
    </Spaces.Fill>
</Spaces.ViewPort>
```

**Comment by aeagle** [comment]
@Slapbox  I can certainly expose more of the React events on the inner div to the space props. 

I do intend on cleaning up the markup later on with a few ideas as I would like to reduce the "`div` hell" produced. The inner and outer divs are only required if a space is resizable and scrollable to allow the resize handle to be placed correctly. Any other space variations could do with a single div.

**Comment by Slapbox** [comment]
That sounds awesome!  It's not a very big deal at all, but it's definitely a nice-to-have.

**Comment by aeagle** [comment]
@Slapbox I've added the onMouseMove, onTouchStart, onTouchMove and onTouchEnd events to the spaces now.

**Comment by Slapbox** [comment]
Very cool! I'll give them a shot when I get things working a bit better; not ready to throw more variables into my debugging yet.
