### ISSUE TITLE
Switching elements does not update positions correctly

### ISSUE THREAD

**Issue by Kilian** [aeagle/react-spaces#52]
**Describe the bug**
I have a site where I have a sidebar that people can toggle between being shown on the right and on the bottom. When I toggle between these by changing the element from Space.RightResizable to Space.BottomResizable, the new situation is calculated as if the old sidebar was still in place. 

**To Reproduce**
See https://codesandbox.io/s/festive-mcclintock-pujdo Press "Toggle side" a few times, and see the sidebar eat away more and more of the main content.

**Expected behavior**
I expect the sidebar to be placed in accordance to the surrounding Space.Viewport without taking into account the old sidebar element.

Strangely enough, when you switch between a Space.RightResizable and no element (`<> </>`) the calculation does use the "new" situation".

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 78

**Comment by aeagle** [comment]
Hi @Kilian 

I am still trying to fix this bug. For some reason the space is taking into account itself in it's old position when recalculating it's new position.

However, in your case you should use a `Space.Custom` which allows you to modify the anchor via a property like so:

https://codesandbox.io/s/hungry-sutherland-psvkd

This will also ensure that the contents of your space are not unnecessarily re-rendered when the space changes anchor type and position.

**Comment by Kilian** [comment]
Switching to `Space.Custom` works, thanks :) There's some additional complexity there when you also want the space to be resizable in both directions and store the width/height separately but I haven't managed to get that into a clear example yet.

**Comment by aeagle** [comment]
The revised internals in the 0.2.0 beta should now deal with switching of different types of space properly as described in the initial issue. Latest beta version is ```v0.2.0-beta.3```. The recommendation is still to use ```<Space.Custom />``` in this circumstance to avoid the reparenting of child components within the space.

I'll close this issue in regards to the latest released version with the recommendation to use ```<Space.Custom />```.
