### ISSUE TITLE
Css height need ';'

### ISSUE THREAD

**Issue by julien-delenclos** [aeagle/react-spaces#56]
**Describe the bug**
Missing ';' in [HeadStyles.tsx](https://github.com/aeagle/react-spaces/blob/master/react-spaces/src/HeadStyles.tsx#L40)
Change ```css.push(`height: ${style.height}`);```
To ```css.push(`height: ${style.height};`);```

**To Reproduce**
1 - Create Layer with z-index,
2 - Add Top element with % size
3 - Style is 
```
{
    left: 0;
    top: 0;
    right: 0;
    height: 25% z-index: 1000;
}
```

**Expected behavior**
```
{
    left: 0;
    top: 0;
    right: 0;
    height: 25%;
    z-index: 1000;
}
```

**Comment by aeagle** [comment]
hi @julien-delenclos. I've release version `0.1.23` which fixes this.
