### ISSUE TITLE
Changelog plans?

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#57]
Hey @aeagle, I was reviewing packages to update and I was excited to see `react-spaces` on the list of updated packages. I was wondering what's changed though? I took a glance at the commits, but nothing's as good as a changelog. I know the library is still in version `0.x`, so no changelog is entirely understandable - but is there any chance we could get a `changelog.md` or release notes on the release page?

Thank you again for all your hard work and for sharing it with us all.

**Comment by aeagle** [comment]
Hi @Slapbox. Currently I'm keeping the change log on my site https://www.allaneagle.com/projects/react-spaces/history (although missing the last version). Though I agree, I need to probably keep one in the repository too.

**Comment by Slapbox** [comment]
Awesome! Thanks for the info.

In the interim, maybe the easiest thing to do is to make a `changelog.md` and just link to https://www.allaneagle.com/projects/react-spaces/history from there

**Comment by aeagle** [comment]
Thanks for the suggestion @Slapbox. I've added the change log with the link now.

**Comment by Slapbox** [comment]
@aeagle React-Spaces continues to work great for us. Thank you so much for your continued work developing this library!

I was just wondering if there are plans to update the changelog for versions `0.2.0` and above?

**Comment by aeagle** [comment]
Hiya @Slapbox. I'm starting to use the GitHub releases now to keep the change history - https://github.com/aeagle/react-spaces/releases

I will get round to pointing various bits to that.
