### ISSUE TITLE
Add onResizeComplete prop to resizable components

### ISSUE THREAD

**Issue by guidogast** [aeagle/react-spaces#58]
**Is your feature request related to a problem? Please describe.**
The only way to get the heights and widths of the resizable components is to nest an Info element inside of it. This also triggers for every small change and can cause performance issues when you want to save the sizes to a server for example. 

**Describe the solution you'd like**
I'd like to see an onResizeComplete functions as a prop that triggers when you release the mouse and passed the new width and height as parameters.

**Describe alternatives you've considered**
A debounce could be used but is not ideal, since you don't really have a trigger when the drag is completed, plus it triggers too often.

**Comment by aeagle** [comment]
Hi @guidogast. There is actually a way to hook into the start/end resize events as described here https://github.com/aeagle/react-spaces/issues/32#issuecomment-544297570. Let me know if that solves your problem.

**Comment by guidogast** [comment]
Thanks! I overlooked the issue, sorry about that. However I would recommend updating the documentation on the website by adding all possible props. That will make things a lot more clear in the future :)

**Comment by aeagle** [comment]
No problem, glad that helped. I do plan to setup a storybook with full documentation shortly. See #59.
