### ISSUE TITLE
Possible side effect in other components  (warning with React 16.13.0)

### ISSUE THREAD

**Issue by thoomasbro** [aeagle/react-spaces#64]
**Describe the bug**
When using react 16.13.0 a new warning appears:
"Cannot update a component from inside the function body of a different component"

**To Reproduce**
1. Go to https://codesandbox.io/s/react-spaces-y0q3n
2. see warnings in console

**Expected behavior**
no warnings

**Comment by pLavrenov** [comment]
any ideas?

**Comment by aeagle** [comment]
Hey all. Could you try version ```v0.2.0-beta.3``` to see if this removes the warning for you?

**Comment by aeagle** [comment]
I've released `v0.2.0` now which should resolve this issue. Feel free to reopen this issue if you are still having problems.
