### ISSUE TITLE
0.1.25 breaks existing implementation

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#70]
**Describe the bug**
I won't have time to document this well and we're opting to stay on `0.1.25`, but I wanted to report that code we have that collapses the space when it's dragged to a size smaller than the minimum defined no longer works properly.

Is there any changelog for versions beyond `0.1.23`? Maybe that will make it obvious where things are going wrong.

**Desktop (please complete the following information):**
 - Browser `Electron@8.2.x`
 - Version `0.1.25`

**Comment by aeagle** [comment]
Hi @Slapbox - sorry refer to https://www.allaneagle.com/react-spaces/docs/?path=/docs/react-spaces-change-history--page

There is a refactor in `0.1.25` which involves the resizing which was intended as preparation for future enhancements but it sounds like this has caused you issues.

I'm moving things around at the moment and in the middle of a rewrite of spaces (see #69 for details). It might be worth sticking on the version that works for you at the moment and moving to the newer version once the rewrite is finished in relation to #69.

**Comment by Slapbox** [comment]
I'm very happy on `0.1.24` and ready to stay put for a while. Just wanted to give you a heads up that something had functionally changed.

Thanks for the update and your great work @aeagle.

**Comment by Kilian** [comment]
Can confirm that for custom spaces, `minimumSize` seems to no longer be applied either

**Comment by aeagle** [comment]
Could be related to issue #73 with fix currently being reviewed on PR #74. Need to check after PR #74 applied.

**Comment by aeagle** [comment]
@Slapbox There is a small possibility that your issue with `v0.1.25` has been fixed with a fix applied in #74 which has been release in `v0.1.26`.

**Comment by Slapbox** [comment]
@aeagle thanks for the follow-up! I actually scrapped my existing code and have been rewriting it from scratch (still using React-Spaces, it's so great!)

My guess though is that #74 would have fixed my issue though, so I'll close this.

Thanks again for all your help and awesome work!
