### ISSUE TITLE
handleSize seems to be ignored on Custom spaces, always 5px

### ISSUE THREAD

**Issue by Slapbox** [aeagle/react-spaces#79]
**Describe the bug**

**To Reproduce**
<Spaces.Custom handleSize={1} >{children}</Spaces.Custom>

**Expected behavior**
Resizer should have a width of 1px when passing `handleSize={1}`.

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Electron
 - Version 8.5.x

**Comment by aeagle** [comment]
Hi @Slapbox 

This has been fixed in #80 and released in ```v0.1.27```

**Comment by aeagle** [comment]
Hi @Slapbox. Feel free to reopen if you are still getting this issue in the latest release version `v0.1.29`

**Comment by Slapbox** [comment]
Hey @aeagle thanks for the update, I just got a chance to test it and it looks good! Thanks again for sharing this beautiful library!
