### ISSUE TITLE
`onResizeEnd` doesn't respect `maximumSize` if `size` === `maximumSize`

### ISSUE THREAD

**Issue by verbold** [aeagle/react-spaces#86]
**Describe the bug**
If a resizable element's `size` equals its `maximumSize`, a user can resize the element beyond the `maximumSize`.

**To Reproduce**
1. Go to [https://codesandbox.io/s/naughty-hertz-kuis1?file=/src/index.js](https://codesandbox.io/s/naughty-hertz-kuis1?file=/src/index.js)
2. Resize the sidebar to its maximum size (`150`) then resize it again to bypass the `maximumSize` prop value.

**Expected behavior**
Element shouldn't be larger than the specified `maximumSize`.

**Package versions:**
 - React version: 17.0.2
 - React spaces version: 0.2.x

**Additional context**
Issue can be solved by checking for `typeof maximumAdjust === "number"` instead of falsy check in `core-resizing.ts`, line 48.

**Comment by aeagle** [comment]
Hi @verbold - your suggested fix has been applied in `v0.2.5` as seen in https://codesandbox.io/s/ecstatic-snowflake-vw5k8?file=/src/index.js
