### ISSUE TITLE
Update peer dependencies for react to include v17

### ISSUE THREAD

**Issue by lcaouen** [aeagle/react-spaces#90]
react-spaces is not compatible with react 17, it needs react 16
we have to use npm i --legacy-peer-deps to be able to use it

do you think an upgrade could be done to make it compatible ?

 - React version: 17.0.1
 - React spaces version: 0.2.1
 - Node : 14

best regards

**Comment by aeagle** [comment]
@lcaouen A code sandbox with the versions you mentioned appears fine - https://codesandbox.io/s/sad-brahmagupta-d5idb?file=/package.json

Could you provide more details as to what in particular is not working? An idea of the peer dependency causing you problems would be useful.

**Comment by lcaouen** [comment]
@aeagle the problem is when you do npm i and when you have react 17 in your package.json
Here is the errror message :
![image](https://user-images.githubusercontent.com/3267663/124253928-d09c2180-db28-11eb-8fc5-b345bdd15622.png)
We have to do npm i --legacy-peer-deps to make npm work
My npm version : 7.14.0
Using React 17 would probably correct some vunerabilities by the way

I don't think you can reproduce it with codesandbox as you don't see the parameters used by npm.

**Comment by aeagle** [comment]
@lcaouen Thanks for the information. I've released a fix in `v0.2.2 which should resolve your issue (solved with #91). Let me know if you are still having problems.

**Comment by lcaouen** [comment]
Thanks for the fix. It works.
